spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eodigakka}
    username: ${DB_USERNAME:eodigakka}
    password: ${DB_PASSWORD:eodigakka}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.eodigakka: debug
