spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

server:
  forward-headers-strategy: framework

logging:
  level:
    root: info
    com.eodigakka: info

app:
  openapi:
    server-url: ${OPENAPI_SERVER_URL:https://api.eodigakka.xyz}
  auth:
    jwt:
      secret: ${JWT_SECRET}
