CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_provider VARCHAR(20) NOT NULL,
    social_id VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    profile_image VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_social_account UNIQUE (social_provider, social_id),
    CONSTRAINT ck_users_social_provider
        CHECK (social_provider IN ('KAKAO', 'GOOGLE')),
    CONSTRAINT ck_users_nickname_not_blank
        CHECK (char_length(btrim(nickname)) > 0)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    description TEXT,
    preferred_area VARCHAR(255),
    notice TEXT,
    host_user_id BIGINT NOT NULL,
    invite_code VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointments_host_user
        FOREIGN KEY (host_user_id) REFERENCES users (id),
    CONSTRAINT uq_appointments_invite_code UNIQUE (invite_code),
    CONSTRAINT ck_appointments_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_appointments_invite_code_not_blank
        CHECK (char_length(btrim(invite_code)) > 0),
    CONSTRAINT ck_appointments_status
        CHECK (status IN ('PLANNING', 'CONFIRMED', 'CLOSED'))
);

CREATE INDEX idx_appointments_host_user_id
    ON appointments (host_user_id);

CREATE INDEX idx_appointments_schedule
    ON appointments (appointment_date, appointment_time);

CREATE TABLE appointment_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    user_id BIGINT,
    member_type VARCHAR(20) NOT NULL,
    guest_name VARCHAR(50),
    guest_token_hash VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_members_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_members_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_appointment_members_user UNIQUE (appointment_id, user_id),
    CONSTRAINT uq_appointment_members_guest_token UNIQUE (appointment_id, guest_token_hash),
    CONSTRAINT uq_appointment_members_guest_name UNIQUE (appointment_id, guest_name),
    CONSTRAINT ck_appointment_members_type
        CHECK (member_type IN ('USER', 'GUEST')),
    CONSTRAINT ck_appointment_members_role
        CHECK (role IN ('HOST', 'MEMBER')),
    CONSTRAINT ck_appointment_members_identity
        CHECK (
            (
                member_type = 'USER'
                AND user_id IS NOT NULL
                AND guest_name IS NULL
                AND guest_token_hash IS NULL
            )
            OR
            (
                member_type = 'GUEST'
                AND user_id IS NULL
                AND guest_name IS NOT NULL
                AND char_length(btrim(guest_name)) > 0
                AND guest_token_hash IS NOT NULL
                AND char_length(btrim(guest_token_hash)) > 0
                AND role = 'MEMBER'
            )
        )
);

CREATE INDEX idx_appointment_members_user_id
    ON appointment_members (user_id);

CREATE TABLE place_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    kakao_place_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    road_address VARCHAR(500),
    category VARCHAR(255),
    place_url VARCHAR(500),
    phone VARCHAR(50),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    added_by_member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_place_candidates_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_candidates_added_by_member
        FOREIGN KEY (added_by_member_id) REFERENCES appointment_members (id),
    CONSTRAINT uq_place_candidates_kakao_place
        UNIQUE (appointment_id, kakao_place_id),
    CONSTRAINT ck_place_candidates_kakao_place_id_not_blank
        CHECK (char_length(btrim(kakao_place_id)) > 0),
    CONSTRAINT ck_place_candidates_name_not_blank
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_place_candidates_address_not_blank
        CHECK (char_length(btrim(address)) > 0),
    CONSTRAINT ck_place_candidates_latitude
        CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_place_candidates_longitude
        CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_place_candidates_added_by_member_id
    ON place_candidates (added_by_member_id);

CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    place_candidate_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_votes_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_votes_place_candidate
        FOREIGN KEY (place_candidate_id) REFERENCES place_candidates (id) ON DELETE CASCADE,
    CONSTRAINT fk_votes_member
        FOREIGN KEY (member_id) REFERENCES appointment_members (id) ON DELETE CASCADE,
    CONSTRAINT uq_votes_appointment_member UNIQUE (appointment_id, member_id)
);

CREATE INDEX idx_votes_place_candidate_id
    ON votes (place_candidate_id);

CREATE INDEX idx_votes_member_id
    ON votes (member_id);

CREATE TABLE confirmed_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    place_candidate_id BIGINT NOT NULL,
    confirmed_by_user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_confirmed_places_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_confirmed_places_place_candidate
        FOREIGN KEY (place_candidate_id) REFERENCES place_candidates (id),
    CONSTRAINT fk_confirmed_places_confirmed_by_user
        FOREIGN KEY (confirmed_by_user_id) REFERENCES users (id),
    CONSTRAINT uq_confirmed_places_appointment UNIQUE (appointment_id)
);

CREATE INDEX idx_confirmed_places_place_candidate_id
    ON confirmed_places (place_candidate_id);

CREATE INDEX idx_confirmed_places_confirmed_by_user_id
    ON confirmed_places (confirmed_by_user_id);

CREATE TABLE member_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    accuracy DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_locations_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_locations_member
        FOREIGN KEY (member_id) REFERENCES appointment_members (id) ON DELETE CASCADE,
    CONSTRAINT uq_member_locations_appointment_member UNIQUE (appointment_id, member_id),
    CONSTRAINT ck_member_locations_latitude
        CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_member_locations_longitude
        CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_member_locations_accuracy
        CHECK (accuracy >= 0)
);

CREATE INDEX idx_member_locations_member_id
    ON member_locations (member_id);
