CREATE TABLE guest_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_member_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    CONSTRAINT fk_guest_sessions_appointment_member
        FOREIGN KEY (appointment_member_id) REFERENCES appointment_members (id) ON DELETE CASCADE,
    CONSTRAINT uq_guest_sessions_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_guest_sessions_appointment_member_id
    ON guest_sessions (appointment_member_id);

CREATE INDEX idx_guest_sessions_expires_at
    ON guest_sessions (expires_at);
